= FAQ: Object Store v2
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

== Object Store v2 を使用できるリージョンは?

Object Store v2 は、Runtime Manager (CloudHub) アプリケーションをデプロイできる​xref:runtime-manager::cloudhub-architecture.adoc#global-worker-clouds[リージョンすべて]​で使用できます。

== Object Store v2 をサポートする Mule バージョンは?

Mule 3.8.5 以上、およびすべての 4.x バージョン。

[IMPORTANT]
====

* Mule 4 は Object Store v2 のみをサポートしています。
* CloudHub にデプロイされた Mule Runtime のみが Object Store v2 を使用できます。

====

== サブスクリプションのトランザクション制限に達した場合はどうなりますか?

Object Store v2 サブスクリプションパックによって、Anypoint Platform 組織に 1 か月あたり 1 億件のトランザクションが許可されます。この制限は、すべての本番環境と非本番環境に適用されます。
https://anypoint.mulesoft.com/exchange/portals/anypoint-platform/f1e97bc6-315a-4490-82a7-23abe036327a.anypoint-platform/object-store-v2/[Object Store v2 REST API] を使用して使用状況を監視できます。

トランザクション制限に達した場合、Object Store v2 は機能を継続し、MuleSoft 営業担当から組織に連絡が来て、プランを増やすことができます。

== Object Store v2 はワーカーと同じリージョンで存続しますか?

はい、Object Store v2 は、アプリケーションが最初にデプロイされた、ワーカーと同じリージョンにあります。たとえば、シンガポールリージョンにデプロイした場合、オブジェクトストアはシンガポールリージョンで存続します。

IMPORTANT: 最初のデプロイの後、アプリケーションを別のリージョンに移動した場合、Object Store v2 はデータが失われないように元のリージョンに残ります。使用する Object Store v2 が別のリージョンに移動することはありません。アプリケーションとオブジェクトストアの両方を別のリージョンにデプロイする必要がある場合は、アプリケーションを削除してから新しいリージョンに再アップロードする必要があります。この操作により、ストレージに存在するデータはすべて失われます。

== オブジェクトストアエントリは、どのようにワーカーに分割されますか?

Object Store v2 は、CloudHub とは別個のリモートサービスです。​`_defaultUserObjectStore`​ に配置したすべてのエントリを、同じアプリケーションのすべてのワーカーが使用できます。​`_defaultUserObjectStore`​ を使用していない場合、データはワーカーのメモリ内オブジェクトストアに置かれ、ワーカーが再起動されたり、新しいアプリケーションバージョンがデプロイされたりするとデータは失われます。

使用可能なエントリ数の例として、50 個のエントリと 5 つのワーカーがある場合、アプリケーション内のすべてのワーカーが 50 個のエントリすべてを使用でき、Object Store v2 サービスはワーカーに影響を及ぼさずにすべてのデータの保存を処理します。

== Mule アプリケーションが別のアプリケーションのオブジェクトストアにアクセスする方法は?

他の Mule アプリケーションがアプリケーションのオブジェクトストアにアクセスする必要がある場合、&#8203;https://anypoint.mulesoft.com/exchange/portals/anypoint-platform/f1e97bc6-315a-4490-82a7-23abe036327a.anypoint-platform/object-store-v2/[Object Store v2 REST API] を使用して 1 つのアプリケーションから読み取り、別のアプリケーションに保存します。

== オブジェクトストアの制限は?

オブジェクトストアの合計サイズに制限はありませんが、各値は 10 MB に制限されます。無料バージョンでも 1 秒あたり 10 件のトランザクションに使用が制限されます。プレミアムアドオンユーザは、最大 100 TPS まで使用できます。

== Object Store v2 でのデータ存続期間は?

Object Store v2 のデータは 30 日間存続します。キーが更新されると、有効期間はリセットされます。更新がない場合、キーは 30 日後に削除されます。

== Object Store v2 で存続できるキーの最大数は?

Object Store v2 では、アプリケーションごとのキー数に制限はありません。Object Store v1 では、制限は 100,000 キーで、それを超えて保存を試みると拒否されます。

== Object Store v2 REST API ポータルの場所は?

この API は、&#8203;https://anypoint.mulesoft.com/exchange/portals/anypoint-platform/f1e97bc6-315a-4490-82a7-23abe036327a.anypoint-platform/object-store-v2/[Anypoint Platform 開発者のポータル] で使用できます。

== Object Store Connector の場所は?

https://www.anypoint.mulesoft.com/exchange/?search=objectstore[Anypoint Exchange] で、Anypoint Studio 6 で使用される Mule 3 Object Store Connector および Studio 7 で使用される Mule 4 Object Store Connector のアセットを提供しています。

== Object Store v2 と Object Store v1 で異なる Object Store Connector が必要ですか?

Mule の Object Store Connector は、すべてのバージョンが Object Store v1 と Object Store v2 の両方で動作します。

== Object Store の値がバイナリ形式である理由は?

Runtime Manager で Object Store キーを表示すると、キーは ​`[binary value] BINARY`​ として表示されます。
Mule 4 では、値を Mule オブジェクトでラップして、Anypoint Platform で値がバイナリでのみ表示されるようにします。バックグラウンドでは、Mule 4 が Mule 内部シリアライザでバイナリ逐次化を実行します。ユーザインターフェースではオブジェクトを非逐次化できないため、値がバイナリになったことのみが伝えられます。

キー値を表示するには、アプリケーションのコネクタに次のような Object Store 取得フローが必要です。

[source,xml,linenums]
----
<flow name="Retrieve" >
	<http:listener doc:name="Listener" config-ref="HTTP_Listener_config1"
		path="/retrieve">
		<ee:repeatable-file-store-stream />
	</http:listener>
	<os:retrieve doc:name="Retrieve"
		key="#[attributes.queryParams.key]"
		objectStore="Object_store1"/>
</flow>
----

詳細は、​xref:osv2-tutorial.adoc#create-a-studio-7-project[「チュートリアル: Studio 7 プロジェクトを作成する」]​を参照してください。

== Object Store v2 にレート制限はありますか?

Object Store SKU を別途購入していないお客様には、アプリケーションあたり 10 TPS (トランザクション/秒) というレート制限があります。  Object Store v2 SKU を購入していないアカウントでアプリケーションがレート制限を超えると、それ以降しばらくの間、要求は処理されず、429 HTTP エラー状況コードが返されます。基本となる 10 TPS のレート制限を超える場合は、MuleSoft アカウントチームまでお問い合わせください。

== Object Store v2 データの保護方法は?

Object Store v2 では、セキュアなトランスポートに TLS を使用します。保管時のデータは、FIPS 140-2 準拠の暗号化標準を使用して保存されます。  より高いレベルのセキュリティが必要な場合、機密データは暗号化してからオブジェクトストアに書き出すことをお勧めします。

== Object Store ではデータはキャッシュされますか、それとも読み書きのたびに I/O が行われますか?

Object Store では読み書きのたびに I/O が行われます。Object Store v2 では、API コールは、Runtime Manager アプリケーションと同じデータセンターに限定されます。

== 関連資料

* https://anypoint.mulesoft.com/exchange/portals/anypoint-platform/f1e97bc6-315a-4490-82a7-23abe036327a.anypoint-platform/object-store-v2/[Anypoint Exchange Object Store v2]
* https://www.anypoint.mulesoft.com/exchange/org.mule.connectors/mule-objectstore-connector/[Mule 4 Object Store Connector]
* https://www.anypoint.mulesoft.com/exchange/org.mule.modules/mule-module-objectstore/[Object Store Connector - Mule 3]
* https://forums.mulesoft.com/search.html?q=object+store[「Object Store」MuleSoft フォーラム]
* https://support.mulesoft.com/s/global-search/%40uri#q=object%20store&t=AllResults[Object Store に関する知識ベース記事]
